In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
A = np.array([[3+2, 8+1], [2*3, 8+2]])
print(A)

[[ 5  9]
 [ 6 10]]


In [3]:
# 1. shape
dims = np.shape(A)
print("Dimensions: ", dims)

# 2. Determinant
det_val = np.linalg.det(A)
print("Determinant:", det_val)

# 3. Inverse matrix check
if det_val != 0:
    inv_mat = np.linalg.inv(A)
else:
    inv_mat = "Not possible"

print("Inverse:", inv_mat)

# Rank of matrix
mat_rank = np.linalg.matrix_rank(A)
print("Rank:", mat_rank)

# Eigenvalues and eigenvectors
eig_vals, eig_vecs = np.linalg.eig(A)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)


Dimensions:  (2, 2)
Determinant: -4.000000000000007
Inverse: [[-2.5   2.25]
 [ 1.5  -1.25]]
Rank: 2
Eigenvalues: [-0.26208735 15.26208735]
Eigenvectors:
 [[-0.86327385 -0.659362  ]
 [ 0.50473582 -0.75182561]]


In [4]:
B = np.array([[3+2+1, 8+1],
              [2*3,   8+2]])
print(B)

[[ 6  9]
 [ 6 10]]


In [5]:
# 1. shape
dims = np.shape(B)
print("Dimensions: ", dims)

# 2. Determinant
det_val = np.linalg.det(B)
print("Determinant:", det_val)

# 3. Inverse matrix check
if det_val != 0:
    inv_mat = np.linalg.inv(B)
else:
    inv_mat = "Not possible"

print("Inverse:", inv_mat)

# Rank of matrix
mat_rank = np.linalg.matrix_rank(B)
print("Rank:", mat_rank)

# Eigenvalues and eigenvectors
eig_vals, eig_vecs = np.linalg.eig(B)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)


Dimensions:  (2, 2)
Determinant: 6.0
Inverse: [[ 1.66666667 -1.5       ]
 [-1.          1.        ]]
Rank: 2
Eigenvalues: [ 0.38422689 15.61577311]
Eigenvectors:
 [[-0.84838898 -0.68334334]
 [ 0.52937334 -0.73009717]]


In [6]:
# Determinant change: Compare det_val vs det_B. The difference comes from altering one entry, which shifts the balance of multiplication terms in the determinant formula.

# Rank: If the rows/columns remain linearly independent, rank stays 2. If the change makes them dependent, rank drops.

# Eigenvalues: They shift because the characteristic polynomial changes when any entry is modified.

# Invertibility: If determinant moves closer to 0, matrix B is harder to invert (numerically unstable). If determinant increases in magnitude, inversion is easier.