In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:

# 1. Create two 3×3 matrices with random integers in Python.

X = np.random.randint(10, 25, (3, 3))
Y = np.random.randint(25, 35, (3, 3))

# 2. Perform addition, subtraction, and multiplication operations on these matrices.
sum_matrix = X + Y
diff_matrix = X - Y
prod_matrix = X @ Y


print("Sum:\n", sum_matrix)
print("Difference:\n", diff_matrix)
print("Product:\n", prod_matrix)

# 3. Compute the determinant, inverse, and rank of one of the matrices.
det_X = np.linalg.det(X)

if not np.isclose(det_X, 0):
    inv_X = np.linalg.inv(X)
else:
    inv_X = "Matrix is singular, inverse not possible"

rank_X = np.linalg.matrix_rank(X)

print("Determinant:", det_X)
print("Inverse:\n", inv_X)
print("Rank:", rank_X)


Sum:
 [[47 44 36]
 [48 49 47]
 [53 35 43]]
Difference:
 [[-15 -20 -14]
 [ -6  -3 -13]
 [ -7 -15  -9]]
Product:
 [[1150 1099 1046]
 [1782 1695 1657]
 [1493 1421 1317]]
Determinant: 434.99999999999966
Inverse:
 [[ 0.50804598 -0.21609195 -0.11264368]
 [ 0.07816092  0.04367816 -0.09425287]
 [-0.73333333  0.26666667  0.26666667]]
Rank: 3
